### PR TITLE
Multi-notes

### LINKED ISSUE #779: The top part of the "Synced (hour)" button is not clickable
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc3) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the area above the "Synced (hour)" string and observe the behavior.

**[Expected result]:**
- The syncing sequence is started.

**[Actual result]:**
- Nothing happens and the "Sync Your Notes" button is highlighted.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
rec of the issue 2

### PR DESCRIPTION
**Pull request by sebastienbarbier**
Implementing Multi-notes feature using redux data flow.

Still need to be done:
- [x] Integrate multi-notes UI
- [x] Login form do not always open
- [x] Sync do not always solve conflict properly
- [x] Do not share anymore updated text between multiple window.
- [x] Send to notes is broken (need to know which note to populate)
- [x] Display initialData on first start
- [x] Migrate old single note (id="singleNote") to UUID4
- [x] Apply CSS feedbacks (larger menu, semibold font, colors, ...)
- [x] Improve loading to have no lag on display
- [x] Simplify Action.js file (probably just naming convention)
- [x] Make times use Locale format ( 10:43 or March 20, 2018), only update when created or synced (Kinto timestamp?)

## Follow Up Issues

- [ ] Implement dark theme ( https://github.com/mozilla/notes/issues/785 )
- [ ] Send to Note Multi-Window  https://github.com/mozilla/notes/issues/787
- [ ] Performance issue with long text 😖 https://github.com/mozilla/notes/issues/783
- [ ] Keyboard navigation in app https://github.com/mozilla/notes/issues/786
- [ ] Placeholder on empty note https://github.com/mozilla/notes/issues/784

Latest version: [notes_4.0.0-beta.1.zip](https://github.com/mozilla/notes/files/1832122/notes_4.0.0-beta.1.zip) (March 21st)

Fixes #779 #759 #778 #40 #524

### CODE REVIEW

**Comment by vladikoff** [comment]
* [ ] Lost sync state
* [ ] Multi-window type (ignore for now)

File: locales/sr/notes.properties [hunk 1]
```diff
@@ -1,5 +1,45 @@
-welcomeTitle2=Здраво!
-welcomeText2=Добродошли на једностранични нотес уграђен у Firefox. Сурфујте вебом. Запишите белешке. Једноставно је.
+welcomeTitle3=Добродошли у Firefox Notes!
```
Comment (flodolo) [inline locales/sr/notes.properties]: Uhm, why do you have change to the Serbian localization in your PR?

File: locales/en-US/notes.properties [hunk 2]
```diff
@@ -48,9 +48,11 @@ emptyPlaceHolder=Take a note…
 giveFeedback=Click here to give us some feedback
 feedback=Give Feedback
 cancelLogin=Cancel Login
+cancelSetup=Cancel Setup
```
Comment (flodolo) [inline locales/en-US/notes.properties]: What's "Setup" in this context?

**Comment by sebastienbarbier** [comment]
**Oups** 😱, I did some mess here by merged multi-notes prototype into redux which added like 20 commits ... making this PR difficult to follow. 
@flodolo **no idea why serbian localization has been edited.** I do not even understand how that's possible ... **need to investigate**  that point 🤔, thanks a lot for pointing this. English udpate come from ryan latest [design reference](https://mozilla.invisionapp.com/share/6VBUYHMRB#/281041484_Firefox_Notes) regarding multi-notes. I was not expecting you to receive notifications from this yet.

**Comment by flodolo** [comment]
> I was not expecting you to receive notifications from this yet.

That's automatic, as soon as a commit touches the .properties file. No damage done anyway ;-)

Thanks for the pointer to the design reference, I'll take a look.

**Comment by flodolo** [comment]
> Thanks for the pointer to the design reference, I'll take a look.

Either the [link](https://mozilla.invisionapp.com/share/6VBUYHMRB#/281041484_Firefox_Notes) is private, or moved?

File: locales/sr/notes.properties (hunk 1 above)
Comment (sebastienbarbier) [reply locales/sr/notes.properties]: Serbian modifications come from a commit done yesteday on master ...  I don't understand why my PR see a diff here with master since on master I have same version ...

**Comment by sebastienbarbier** [comment]
I confirme link is dead, @ryanfeeley can you check why link on README.md to multi note design reference is not working anymore 😢

File: locales/sr/notes.properties (hunk 1 above)
Comment (flodolo) [reply locales/sr/notes.properties]: Wild guess: at this point your PR touches the file twice, so it's like a standard modification that was committed only on the branch. I think you have to manually restore the file from master and commit to the branch.

Note that there are a few other conflicts against master (but not the Serbian file).

**Comment by sebastienbarbier** [comment]
@flodolo Serbian localization issue is solved, you were right my merge from master was not done properly 👍. Thanks a lot for your input.

File: locales/en-US/notes.properties (hunk 2 above)
Comment (sebastienbarbier) [reply locales/en-US/notes.properties]: I have a screenshot (to keep working if this kind of thing happen), but might be deprecated at any time.
capture d ecran 2018-03-08 a 07 41 57

**Comment by ryanfeeley** [comment]
@sebastienbarbier Looks like Invision is down for maintenance. Hmmm… http://status.invisionapp.com/

Get you a PDF on Slack.

File: locales/en-US/notes.properties (hunk 2 above)
Comment (flodolo) [reply locales/en-US/notes.properties]: Thanks. So, I guess "Setup" stands for login+verification.

Comment (sebastienbarbier) [reply locales/en-US/notes.properties]: I feel like that's the prefect way to say it, YES! 😍

**Comment by sebastienbarbier** [comment]
Awesome so it should be back soon 👍, well done ryan. Please no rush for the PDF, I have screenshots on my machine and I guess we can wait for invision to be back.

**Comment by sebastienbarbier** [comment]
First draft to play with the UI, no sync and no multinote but first note in the list reflect real content 👍
[notes_4.0.0-alpha.1.zip](https://github.com/mozilla/notes/files/1802874/notes_4.0.0-alpha.1.zip)

File: src/sidebar/app/components/EditorPanel.js [hunk 3]
```diff
@@ -1,23 +1,64 @@
...
 
+import { createNote } from '../actions';
+
 class EditorPanel extends React.Component {
 
+  constructor(props) {
+    super(props);
+    this.props = props;
+
+    this.note = {}; // Note hsould be reference to state.
```
Comment (vladikoff) [inline src/sidebar/app/components/EditorPanel.js]: hsould ⌨️

**Comment by sebastienbarbier** [comment]
[notes_4.0.0-alpha.2.zip](https://github.com/mozilla/notes/files/1815578/notes_4.0.0-alpha.2.zip)

Missing features : 
- [ ] Send to notes is broken (need to know which note to populate)
- [ ] Display initialData on first start
- [ ] Placeholder on empty note
- [ ] Migrate old single note (id="singleNote") to UUID4
- [ ] Apply CSS feedbacks (larger menu, semibold font, colors, ...)
- [ ] Improve loading to have no lag on display
- [ ] Implement dark theme

Still need to review redux process (missing kinto-sync event 😰), and to improve overall stability.

File: locales/en-US/notes.properties [hunk 4]
```diff
@@ -114,3 +117,7 @@ darkThemeTitle=Dark
 sendToNotes=Send to Notes
 
 exportAsHTML=Export as HTML…
+
+newNote=New Note
+makePlainText=Make Plain Text
```
Comment (vladikoff) [inline locales/en-US/notes.properties]: we can add the string for translation but maybe not worry about this feature for now?

File: src/sidebar/app/components/ListPanel.js [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+        <ul>
+          { this.props.state.notes.filter((note) => note.firstLine ).sort((a, b) => {
+            if (a.lastModified.getTime() !== b.lastModified.getTime()) {
+              return a.lastModified.getTime() < b.lastModified.getTime() ? 1 : -1;
+            }
+            return a.firstLine < b.firstLine ? 1 : -1;
+          }).map((note) => {
+            return (
+              <li key={note.id}>
+                <Link to={`/note/${note.id}`}
```
Comment (vladikoff) [inline src/sidebar/app/components/ListPanel.js]: might have to change these to `Button` to avoid middle-clic, drag issue

**Comment by vladikoff** [comment]
@sebastienbarbier found this, it is creating new ck-body divs when switching between notes:

**Comment by vladikoff** [comment]
@cedricium check this out ^ see if you find any issues, also check the code if you have time :)

**Comment by cedricium** [comment]
I'll try out the zip file @sebastienbarbier added a few comments above, but I'm not able to run `npm install` successfully on this `redux` branch.

I tried deleting `node_modules/` and retrying but this still happens... 🤔 

```
ERROR in ../node_modules/css-loader??ref--1-1!../node_modules/sass-loader/lib/loader.js!../node_modules/@ckeditor/ckeditor5-heading/theme/theme.scss
Module build failed:
@import '~@ckeditor/ckeditor5-theme-lark/theme/helpers/_spacing';
^
      File to import not found or unreadable: ~@ckeditor/ckeditor5-theme-lark/theme/helpers/_spacing.
Parent style sheet: stdin
      in /Users/cedricamaya/Documents/GitHub/notes/node_modules/@ckeditor/ckeditor5-heading/theme/theme.scss (line 4, column 1)
 @ ../node_modules/@ckeditor/ckeditor5-heading/theme/theme.scss 4:14-113
 @ ../node_modules/@ckeditor/ckeditor5-heading/src/heading.js
 @ ./src/ckeditor.js

ERROR in ./src/strikeengine.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-engine/src/conversion/buildmodelconverter' in '/Users/cedricamaya/Documents/GitHub/notes/ckeditor-build/src'
 @ ./src/strikeengine.js 11:0-96
 @ ./src/strike.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-heading/src/headingengine.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-engine/src/conversion/buildmodelconverter' in '/Users/cedricamaya/Documents/GitHub/notes/node_modules/@ckeditor/ckeditor5-heading/src'
 @ ../node_modules/@ckeditor/ckeditor5-heading/src/headingengine.js 11:0-96
 @ ../node_modules/@ckeditor/ckeditor5-heading/src/heading.js
 @ ./src/ckeditor.js

ERROR in ./src/strikeengine.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-engine/src/conversion/buildviewconverter' in '/Users/cedricamaya/Documents/GitHub/notes/ckeditor-build/src'
 @ ./src/strikeengine.js 12:0-94
 @ ./src/strike.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-heading/src/headingengine.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-engine/src/conversion/buildviewconverter' in '/Users/cedricamaya/Documents/GitHub/notes/node_modules/@ckeditor/ckeditor5-heading/src'
 @ ../node_modules/@ckeditor/ckeditor5-heading/src/headingengine.js 12:0-94
 @ ../node_modules/@ckeditor/ckeditor5-heading/src/heading.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-heading/src/heading.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-ui/src/dropdown/list/createlistdropdown' in '/Users/cedricamaya/Documents/GitHub/notes/node_modules/@ckeditor/ckeditor5-heading/src'
 @ ../node_modules/@ckeditor/ckeditor5-heading/src/heading.js 12:0-93
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/components/toolbar/toolbar.css
Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| @import "../../mixins/_unselectable.css";
|
| .ck-toolbar {
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/toolbar/toolbarview.js 18:0-52
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditoruiview.js
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditor.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/components/button/button.css
Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| @import "../../mixins/_unselectable.css";
| @import "../tooltip/mixins/_tooltip.css";
|
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/button/buttonview.js 16:0-50
 @ ./src/strike.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/globals/globals.css
Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| @import "./_hidden.css";
| @import "./_reset.css";
| @import "./_zindex.css";
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/view.js 19:0-38
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/button/buttonview.js
 @ ./src/strike.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-basic-styles/theme/code.css
Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| .ck-content code {
| 	background-color: hsla(0, 0%, 78%, 0.3);
| 	padding: .15em;
 @ ../node_modules/@ckeditor/ckeditor5-basic-styles/src/code.js 14:0-27
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/components/panel/stickypanel.css
Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| .ck-editor {
| 	& .ck-sticky-panel {
| 		& .ck-sticky-panel__content_sticky {
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/panel/sticky/stickypanelview.js 15:0-57
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditoruiview.js
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditor.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-editor-classic/theme/classiceditor.css
Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| .ck-editor {
| 	/* All the elements within `.ck-editor` are positioned relatively to it.
| 	 If any element needs to be positioned with respect to the <body>, etc.,
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditoruiview.js 15:0-36
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditor.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/components/label/label.css
Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| .ck-label {
| 	display: block;
| }
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/label/labelview.js 12:0-48
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/editorui/boxed/boxededitoruiview.js
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditoruiview.js
 @ ../node_modules/@ckeditor/ckeditor5-editor-classic/src/classiceditor.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/components/tooltip/tooltip.css
Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type.
|  */
|
| .ck-tooltip,
| .ck-tooltip__text::after {
| 	position: absolute;
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/tooltip/tooltipview.js 12:0-52
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/button/buttonview.js
 @ ./src/strike.js
 @ ./src/ckeditor.js

ERROR in ../node_modules/@ckeditor/ckeditor5-ui/theme/components/icon/icon.css
Module parse failed: Unexpected token (6:12)
You may need an appropriate loader to handle this file type.
|  */
|
| svg.ck-icon {
| 	vertical-align: middle;
| }
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/icon/iconview.js 14:0-46
 @ ../node_modules/@ckeditor/ckeditor5-ui/src/button/buttonview.js
 @ ./src/strike.js
 @ ./src/ckeditor.js
```

**Comment by vladikoff** [comment]
@cedricium are you on node 8?

**Comment by cedricium** [comment]
@vladikoff yea, 8.9.4. I actually just had to restart Firefox because after opening a new note, typing some stuff (which was really laggy), then going back to the main page to create a new note caused my Firefox to freeze up :(

Will do some more debugging to see if I can reproduce the issue.

**Comment by vladikoff** [comment]
@cedricium is that with sync enabled?

**Comment by sebastienbarbier** [comment]
@cedricium Is that using npm start or using the old zip from alpha 2 ?!
I’ll be at the office in 20min and give a look what it could be 👍

**Comment by cedricium** [comment]
@vladikoff sync enabled as in `about:preferences`? If so, then yes I have sync enabled.
@sebastienbarbier this was using `notes_4.0.0-alpha.1.zip`, by manually selecting the `manifest.json` file in `about:debugging`.

**Comment by cedricium** [comment]
Just tried adding the manifest.json to FF again, laggy-ness is no longer present and navigating between notes is smooth, no problems. Before, I did have three windows open so not sure if that's a factor.

**Comment by sebastienbarbier** [comment]
Omg, alpha 1 and 2 are full of bugs you'll have a hard time trying to use it 🤣.
I will build a new version but I am having some issues with `npm run build-ck` ...

**Comment by sebastienbarbier** [comment]
@cedricium Please try this lovely alpha.3 😁. Beta 1 should be release today or later this week.
[notes_4.0.0-alpha.3.zip](https://github.com/mozilla/notes/files/1831982/notes_4.0.0-alpha.3.zip)

**Comment by vladikoff** [comment]
> I tried deleting `node_modules/` and retrying but this still happens... 🤔

@cedricium regarding that, what might have happened was - you installed the CKEditor branch, that modified the package lock and then you installed this branch, but it used the updated package lock and fetched the wrong dependencies. 💻

**Comment by sebastienbarbier** [comment]
Releasing beta 1 🎉.
@ryanfeeley please let us know if you have any UI feedbacks
@vladikoff you can test, review, and share with Softvision if you feel like this good.
@cedricium a lots of energy has been put in this version, I hope you will like it 👍. Feel free to share any thoughts about it, all feedbacks are welcome.
[notes_4.0.0-beta.1.zip](https://github.com/mozilla/notes/files/1832122/notes_4.0.0-beta.1.zip)

**Comment by cedricium** [comment]
@sebastienbarbier this is super cool! I really think all of our users will be happy to get this in their hands once its released - very clean UI and it works really good. Keep up the amazing effort 🎉 

One thing I noticed (which might be related to @vladikoff's multiple `ck-body` divs):
 - installed the v4.0.0-beta
 - single note with welcome message was open
 - went to create a new note --> everything all good so far, no issues
 - signed into FxA to enable sync
 - after sync was complete, lots of excessive notes with just this content:
```
undefined
**** On this computer: ****
undefined
```

**Screenshot:**
screen shot 2018-03-21 at 9 49 28 am

**Comment by sebastienbarbier** [comment]
Thanks a lot for your feedbacks, I hope people will like and use it 🤗.

That’s a silly bug you found, but that’s awesome i’ll investigate tomorrow should not be much ... did you have more than one Firefox window open when syncing ?!

**Comment by ryanfeeley** [comment]
Brings up the question: what do we title of a conflicted note?

**Local copy of {Note Title}"**

Something like that?

**Comment by cedricium** [comment]
@sebastienbarbier yes, I had two windows open at the time of syncing.

**Comment by sebastienbarbier** [comment]
@ryanfeeley Right now we merge each note with the following logic : `remote.content + '<p>${mergeWarning}</p>' + local.content`. So default behaviour is to display first line. May be UI should explicitely display a warning about having an unsolved conflict ?

@cedricium awesome I will investigate but having multiple window is more than likely related! Thanks again.
