### PR TITLE
Disallow click event during syncing

### LINKED ISSUE #708: Disable the "Sync Your Notes" button while "Syncing changes" status is displayed
**[Notes]:**
- If the "Sync Your Notes" button is active and actionable while the "Syncing changes" status is displayed, then the behavior from issue #479 will be reproducible again.

**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.0.0rc2) installed.
- You are logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Write something in the sidebar.
3. Observe the "Sync Your Notes" button while the "Syncing changes" status is displayed.

**[Expected result]:**
- The "Sync Your Notes" button is inactive.

**[Actual result]:**
- The "Sync Your Notes" button is active and actionable. 

**[Additional Notes]:**
- Attached a screen recording of the issue:
rec of the issue

### PR DESCRIPTION
**Pull request by sebastienbarbier**
Simply add On click a check in current state if footer is clickable or not.
Fix #708

### CODE REVIEW

File: src/sidebar/app/components/Footer.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ class Footer extends React.Component {
 
     this.enableSyncAction = () => {
       // persist reconnect warning, do not override with the 'saved at'
-      if (this.state.state.ignoreChange) return;
+      if (this.state.state.ignoreChange || !this.state.state.isClickable) return;
```
Comment (Natim) [inline src/sidebar/app/components/Footer.js]: Is `this.state.state.isClickable` enough?
