### PR TITLE
Fix that thing when there are extra spaces in initial content

### LINKED ISSUE #623: The INITIAL_CONTENT text does not disappear after logging into "Firefox Notes"
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button.
3. Insert you credentials and click the "Sign in" button. 
4. Observe the content displayed in the sidebar.

**[Expected result]:**
- Only the synced content is displayed in the sidebar.

**[Actual result]:**
- The placeholder text is displayed in the sidebar under the synced content.

**[Additional Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
rec of the issue

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #623

### CODE REVIEW

**Comment by Natim** [comment]
:mindblown:

File: src/sidebar/panel.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ ClassicEditor.create(document.querySelector('#editor'), {
         if (isFocused || name === 'rename' || name === 'insert') {
           const content = editor.getData();
           if (!ignoreNextLoadEvent && content !== undefined &&
-              content.replace(/&nbsp;/g, ' ') !== INITIAL_CONTENT) {
+              content.replace(/&nbsp;/g, ' ') !== INITIAL_CONTENT.replace(/\s\s+/g, ' ')) {
```
Comment (vladikoff) [inline src/sidebar/panel.js]: l10n may add extra spaces and this will not match, watch out for that, we add the .replace
