### PR TITLE
Sync across profile

### LINKED ISSUE #858: The Notes List is not correctly synchronized across Firefox profiles when a note is deleted
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with the latest Notes version (4.0.0 Beta 5) enabled.
- You must be logged with the same "Firefox Notes" account on both profiles.
- Make sure you have the same notes in the "Note List" View on both profiles.

**[Steps to reproduce]:**
1. Open two browser instances with the profiles from prerequisites.
2. Focus the first browser instance and delete any note.
3. Wait until the "Synced (hour)" message is displayed in the "Notes List" View.
4. Focus the other browser instance and click the "Sync Your Notes" button from the bottom-right part of the sidebar.
5. Observe the notes in the "Notes List" View.

**[Expected result]:**
- The same notes are displayed in the "Notes List" view on both browser instances.

**[Actual result]:**
- The deleted note on the first browser instance is still displayed in the second one.

**[Notes]:**
- The issue is reproducible also on two different devices which are synced with the same Firefox Notes profile.
- Attached a screen recording of the issue:
deleted_notes

### LINKED ISSUE #872: "Send to Notes" creates a new note but does not sync the new note
@sebastienbarbier see https://github.com/mozilla/notes/commit/c420ae8d26dc706f74d7a5dab704d666ef13a524#diff-4e21b49273243fca121200053b009515R114

I had to make the change to update the synced status in that PR but it doesn't actually send the new note to kinto. What should we use there?

### PR DESCRIPTION
**Pull request by sebastienbarbier**
Implement proper syncing by manually tracking lastSync event.

delete

Fix #858 Fix #872

### CODE REVIEW

File: src/sidebar/app/actions.js [hunk 1]
```diff
@@ -101,7 +101,8 @@ export function createNote(content = '', origin) {
     id,
     content,
     origin,
-    lastModified: new Date()
+    lastModified: new Date(),
```
Comment (Natim) [inline src/sidebar/app/actions.js]: This is a bit tedious, we shoud use the server timestamp here. I think Kinto.js is supposed to keep it :/

Comment (Natim) [reply src/sidebar/app/actions.js]: https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L286

File: src/sync.js [hunk 2]
```diff
@@ -202,6 +204,8 @@ function syncKinto(client, credentials) {
       });
     })
     .then(syncResult => {
+      lastSyncTimestamp = new Date().getTime(); // eslint-disable-line no-undef
```
Comment (Natim) [inline src/sync.js]: This is a bit tedious, we shoud use the server timestamp here. I think Kinto.js is supposed to keep it :/
https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L286

File: src/sidebar/app/actions.js (hunk 1 above)
Comment (Natim) [inline src/sidebar/app/actions.js]: kinto.js is supposed to add it as soon and only as soon as the record is created remotely.

**Comment by Natim** [comment]
I'm glad you were able to fix the getList to use the `_since` parameter.
However I believe we still have somehow a misuse of kinto.js that we should investigate.

File: src/sidebar/app/actions.js (hunk 1 above)
Comment (sebastienbarbier) [reply src/sidebar/app/actions.js]: This is confusing I agree, but we keep inside our blob an other lastModified date for the UI which is only updated by our redux reducer. Sync event was sometimes changing dates and that was confusing for the user. Also non-synced object had no dates ... so that why. We could have done differently ? 🤔

File: src/sync.js (hunk 2 above)
Comment (Natim) [reply src/sync.js]: Not yet but that's something we should definitely investigate.

Comment (sebastienbarbier) [reply src/sync.js]: That's probably why kinto.js is not handling this by itself and need our dirty patch 😓.

File: src/sidebar/app/actions.js (hunk 1 above)
Comment (Natim) [reply src/sidebar/app/actions.js]: Oh yeah you are right `lastModified` and `last_modified`

Comment (sebastienbarbier) [reply src/sidebar/app/actions.js]: Quick vote @Natim , should I rename it lastEdited to avoid any confusion ?

Comment (Natim) [reply src/sidebar/app/actions.js]: lastModifiedDate ?

**Comment by vladikoff** [comment]
@sebastienbarbier 1-2 tests failing:

```
FAILED TESTS:
  Authorization
    syncKinto
      ✖ should handle a conflict (slow: 1.874 secs)
        Firefox 59.0.0 (Linux 0.0.0)
      No fallback response defined for GET to https://example.com/v1/buckets/default/collections/notes/records?_sort=-last_modified&_since=1523265666782
      FetchMock.prototype.fetchMock@test/dist/unit-bundle.js:54529:10
      timedFetch/<@src/vendor/kinto.js:4064:9
      $Promise@src/vendor/kinto-http.js:596:3141
      timedFetch@src/vendor/kinto.js:4045:14
      _callee3$@src/vendor/kinto.js:4226:24
```

File: src/sync.js (hunk 2 above)
Comment (sebastienbarbier) [reply src/sync.js]: @vladikoff fyi, **PR is working** but this is the dirty solution I had to implement. We keep track in sync.js instead of Kinto.Collection object which return for unknown reason lastModified as `NaN`. Except that point, it's 100% handled by kinto as expected *(no extra fetch as discussed)*.

We might have an issue having some gap between real sync and `new Date()` (could we save that date before requesting so worst case we have extra redundant data from those millisecond on next sync ?).

Once again we're dirty and it shows something is wrong in our process with Kinto. I would suggest to open an extra bug and keep working on it when having more time.

**Comment by sebastienbarbier** [comment]
Found a bug on deletion accorss profile. When syncing while editing a note which has been deleted by an other profile, editor keep the deleted note on display.
bugondeleteeditor

**Comment by sebastienbarbier** [comment]
I applied a fix, and it's pretty clear what is going on having both window next to each other, but might be confusing if you sync and forgot about having deleted that specific note just seeing your editor going blank ... 🤔 ? @vladikoff not best UX but what do you think ?
fixedbugondeleteeditor

**Comment by Natim** [comment]
IMHO it should return to the list of notes in the other editor.
