### PR TITLE
sync footer fixed

### LINKED ISSUE #621: Syncing user footer fixes
Not sure which of these are already fixed, but doesn't hurt to file twice.

1. `Synced at` should just be `Synced`
1. Text should be black
1. Hover text is missing on `Synced` text
1. Hover text should be: `Sync to user@example.com`

synced

### PR DESCRIPTION
**Pull request by anweshknayak**
fixes #621

@Natim @vladikoff  please review

I tried changing the property in notes.property but it didn't seem to work so I did it this way [link](https://github.com/mozilla/notes/pull/639/files#diff-1abf0f3e5a69394934ea8f7b5c521805R122)

### CODE REVIEW

File: locales/en-US/notes.properties [hunk 1]
```diff
@@ -75,7 +75,7 @@ savedComplete2=Saved at {time}
 
 # LOCALIZATION NOTE (syncComplete2): {time} is the time of syncing. Such as 5:33pm or 17:33. If this
 # structure doesn't work for your locale, you can translate this as "Synced ({time})".
-syncComplete2=Synced at {time}
+syncComplete2=Synced
```
Comment (flodolo) [inline locales/en-US/notes.properties]: You can't change an existing string like this, you need a new string ID (and to update the reference in the note)
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings

File: locales/tl/notes.properties [hunk 2]
```diff
@@ -75,7 +75,7 @@ savedComplete2=Saved at {time}
 
 # LOCALIZATION NOTE (syncComplete2): {time} is the time of syncing. Such as 5:33pm or 17:33. If this
 # structure doesn't work for your locale, you can translate this as "Synced ({time})".
-syncComplete2=Synced at {time}
+syncComplete2=Synced
```
Comment (flodolo) [inline locales/tl/notes.properties]: As a general rule, don't change localization files

File: locales/en-US/notes.properties (hunk 1 above)
Comment (anweshknayak) [reply locales/en-US/notes.properties]: @flodolo adding something like *syncComplete3=Synced* would do?

Comment (flodolo) [reply locales/en-US/notes.properties]: Yes. Note that you'd need to remove the existing string if it becomes unused.

File: src/sidebar/panel.js [hunk 3]
```diff
@@ -118,7 +118,9 @@ ClassicEditor.create(document.querySelector('#editor'), {
             waitingToReconnect = false;
             clearTimeout(loginTimeout);
             // set title attr of footer to the currently logged in account
-            footerButtons.title = eventData.profile && eventData.profile.email;
+           
+            const footerButtonMail = "Sync to"
```
Comment (Natim) [inline src/sidebar/panel.js]: This would need to be a new localization string.

Comment (anweshknayak) [reply src/sidebar/panel.js]: @Natim I tried doing the same. But it didn't work
```
 footerButtons.title =  `${browser.i18n.getMessage('localization_string')} ${eventData.profile && eventData.profile.email} `
```

Comment (anweshknayak) [reply src/sidebar/panel.js]: Should I add it for all localization files(languages) and do as above? Do tell me what needs to be done here

Comment (Natim) [reply src/sidebar/panel.js]: Yes probably: `syncToMail=Sync to {mail}` and then: ${browser.i18n.getMessage('syncToMail', eventData.profile.email)}

Comment (Natim) [reply src/sidebar/panel.js]: You would need to run: npm run postinstall to propagate your changes to the localization file.

**Comment by anweshknayak** [comment]
@Natim done with the changes. Thanks a lot 🎉

File: locales/en-US/notes.properties [hunk 4]
```diff
@@ -80,6 +80,8 @@ syncComplete2=Synced at {time}
 # LOCALIZATION NOTE (mergeWarning): This string is displayed in case of a merge conflict during a note sync.
 # It is displayed below the 'synced' notes and above the 'local' notes. It is a visual separator.
 mergeWarning=**** On this computer: ****
+syncToMail=Sync to {mail}
+syncComplete3=Synced
```
Comment (Natim) [inline locales/en-US/notes.properties]: I guess we are missing the time {time} variable here aren't we?

File: locales/en-US/notes.properties [hunk 5]
```diff
@@ -80,6 +80,8 @@ syncComplete2=Synced at {time}
 # LOCALIZATION NOTE (mergeWarning): This string is displayed in case of a merge conflict during a note sync.
 # It is displayed below the 'synced' notes and above the 'local' notes. It is a visual separator.
 mergeWarning=**** On this computer: ****
+syncToMail=Sync to {mail}
```
Comment (Natim) [inline locales/en-US/notes.properties]: Please add a LOCALIZATION NOTE explaining what {mail} is about. (see the mergeWarning LOCALIZATION NOTE above.

File: src/sidebar/styles.css [hunk 6]
```diff
@@ -426,3 +426,7 @@ CKEditor overrides
   box-shadow: none;
 }
 
+.black{
+  color:black;       
+  font-Weight : "bold;"
```
Comment (Natim) [inline src/sidebar/styles.css]: I am not quite sure it should be bold.

File: locales/en-US/notes.properties (hunk 4 above)
Comment (anweshknayak) [reply locales/en-US/notes.properties]: Oops missed it

File: src/sidebar/styles.css (hunk 6 above)
Comment (anweshknayak) [reply src/sidebar/styles.css]: then what should it be ?

Comment (Natim) [reply src/sidebar/styles.css]: I guess `color: black` is sufficient

File: src/sidebar/panel.js [hunk 7]
```diff
@@ -118,7 +118,7 @@ ClassicEditor.create(document.querySelector('#editor'), {
             waitingToReconnect = false;
             clearTimeout(loginTimeout);
             // set title attr of footer to the currently logged in account
-            footerButtons.title = eventData.profile && eventData.profile.email;
+            footerButtons.title = `${browser.i18n.getMessage('syncToMail', eventData.profile.email)}`
```
Comment (Natim) [inline src/sidebar/panel.js]: Maybe we need to do:

```
if (eventData.profile) {
    footerButtons.title = `${browser.i18n.getMessage('syncToMail', eventData.profile.email)}`
}
```

However since #637 landed you might want grab the address differently

**Comment by anweshknayak** [comment]
@Natim done as you requested 😄

**Comment by Natim** [comment]
Merci I will give it a try after my meeting

File: locales/en-US/notes.properties [hunk 8]
```diff
@@ -77,10 +77,18 @@ savedComplete2=Saved at {time}
...
+syncComplete3=Synced {time}
+
+# LOCALIZATION NOTE (syncToMail): {mail} is the email-id of the person currently logged in
+syncToMail=Sync to {mail}
+
 # LOCALIZATION NOTE (mergeWarning): This string is displayed in case of a merge conflict during a note sync.
 # It is displayed below the 'synced' notes and above the 'local' notes. It is a visual separator.
 mergeWarning=**** On this computer: ****
 
+
```
Comment (flodolo) [inline locales/en-US/notes.properties]: Can you remove the extra blank lines?

File: src/sidebar/panel.js [hunk 9]
```diff
@@ -118,7 +118,9 @@ ClassicEditor.create(document.querySelector('#editor'), {
             waitingToReconnect = false;
             clearTimeout(loginTimeout);
             // set title attr of footer to the currently logged in account
-            footerButtons.title = eventData.profile && eventData.profile.email;
+            if (eventData.profile) {
+            footerButtons.title = `${browser.i18n.getMessage('syncToMail', eventData.profile.email)}`
```
Comment (Natim) [inline src/sidebar/panel.js]: indentation error.

**Comment by anweshknayak** [comment]
@Natim done

File: locales/en-US/notes.properties [hunk 10]
```diff
@@ -77,6 +77,12 @@ savedComplete2=Saved at {time}
 # structure doesn't work for your locale, you can translate this as "Synced ({time})".
 syncComplete2=Synced at {time}
 
+# LOCALIZATION NOTE (syncComplete3): {time} is the time of syncing. Such as 5:33pm or 17:33.
+syncComplete3=Synced {time}
+
+# LOCALIZATION NOTE (syncToMail): {mail} is the email-id of the person currently logged in
+syncToMail=Sync to {mail}
```
Comment (Natim) [inline locales/en-US/notes.properties]: @ryanfeeley following @flodolo comment should we turn that into `Sync with {mail]`

**Comment by anweshknayak** [comment]
done changes as per discussion #621

File: locales/en-US/notes.properties [hunk 11]
```diff
@@ -77,6 +77,12 @@ savedComplete2=Saved at {time}
 # structure doesn't work for your locale, you can translate this as "Synced ({time})".
 syncComplete2=Synced at {time}
 
+# LOCALIZATION NOTE (syncComplete3): {time} is the time of syncing. Such as 5:33pm or 17:33.
+syncComplete3=Synced {time}
+
+# LOCALIZATION NOTE (syncToMail): {mail} is the email-id of the person currently logged in
```
Comment (flodolo) [inline locales/en-US/notes.properties]: Small nit on the comment: `{mail} is the email address of the Firefox account in use`.

**Comment by anweshknayak** [comment]
@flodolo @Natim done

**Comment by Natim** [comment]
Thank you @anweshknayak
