### PR TITLE
Fix crash on migration while synced

### LINKED ISSUE #879: Upgrading from Notes v3 to v4 while synced crashes the notepad
### [Description]:

upgrade

### PR DESCRIPTION
**Pull request by sebastienbarbier**
PR fix this issue, but we lose authentication after migration since email was not stored locally in v3. Hope that is ok.

Fix #879

### CODE REVIEW

**Comment by sebastienbarbier** [comment]
Should be good 👍, if we have credential but no email we retrieve user profile and authenticate.
UI is optimistic so we load footer as synced and tooltip display during few seconds 'Synced with ...'.

File: src/sidebar/app/app.js [hunk 1]
```diff
@@ -36,9 +36,18 @@ browser.storage.local.get().then(result => {
...
   const state = JSON.parse(result.redux || '{}');
+
   // We use stored state to propagate actions and avoid keeping
-  if (result.hasOwnProperty('credentials') && state.sync && state.sync.email) {
-    store.dispatch(authenticate(state.sync.email));
+  if (result.hasOwnProperty('credentials')) {
+    if (state.sync && state.sync.email) {
+      store.dispatch(authenticate(state.sync.email));
+    } else {
+      store.dispatch(authenticate('...'));
```
Comment (vladikoff) [inline src/sidebar/app/app.js]: `store.dispatch(authenticate('...')` the `...` looks strange, what does that do?

Comment (sebastienbarbier) [reply src/sidebar/app/app.js]: UI is optimistic so we load footer as synced and tooltip display during few seconds 'Synced with ...'.

File: src/background.js [hunk 2]
```diff
@@ -86,6 +86,18 @@ function sendMetrics(event, context = {}, sync = reduxSync) {
   timeouts[event] = setTimeout(later, 20000);
 }
 
+function fetchProfile(credentials) {
+  fxaFetchProfile(FXA_PROFILE_SERVER, credentials.access_token).then((profile) => {
```
Comment (vladikoff) [inline src/background.js]: this request may fail , for example due to an expired token. 

If this request fails we should just "log out" and user can resignin in that case

File: src/sidebar/app/app.js (hunk 1 above)
Comment (vladikoff) [reply src/sidebar/app/app.js]: ah cool

File: src/background.js (hunk 2 above)
Comment (vladikoff) [reply src/background.js]: basically do we need to catch the error case here or it doesn't matter?

Comment (sebastienbarbier) [reply src/background.js]: I believe logout will occur because kinto-sync will fail using expired credential but just to be sure I pushed a catch sending `reconnect` message.

**Comment by sebastienbarbier** [comment]
Note for future us, we should consider re factoring background.js and sync.js: many functions and start to be too long 😉 ... (ping #822 )

File: src/background.js [hunk 3]
```diff
@@ -227,7 +227,11 @@ browser.runtime.onMessage.addListener(function(eventData) {
       break;
     case 'fetch-email':
       credentials.get().then(received => {
-        fetchProfile(received);
+        fetchProfile(received).catch(e => {
+          chrome.runtime.sendMessage({
```
Comment (vladikoff) [inline src/background.js]: yeeee 👍
