### PR TITLE
Disable sync your notes while editing status is displayed.

### LINKED ISSUE #311: Disable the "Sync Your Notes" button while "Editing" status is displayed
**[Notes]:**
- If you press the "Sync Your Notes" button while "Editing" status is displayed then the old content is redisplayed.

**[Affected versions]:**
- Firefox Notes 2.0.0dev
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0dev) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write something in the "Firefox Notes" sidebar.
3. Observe the "Sync Your Notes" button while the "Editing" status is still displayed.

**[Expected result]:**
- The "Sync Your Notes" button is inactive.

**[Actual result]:**
- The "Sync Your Notes" button is active and actionable.

**[Additional Notes]:**
- Attached a screen recording of the issue:
rec of the issue

### PR DESCRIPTION
**Pull request by Natim**
Fixes #311

### CODE REVIEW

File: src/sidebar/panel.js [hunk 1]
```diff
@@ -333,12 +333,16 @@ closeButton.addEventListener('click', () => {
...
 enableSync.onclick = () => {
+  if (editingInProcess) {
+    return;
+  }
   savingIndicator.textContent = browser.i18n.getMessage('openingLogin');
 
   loginTimeout = setTimeout(() => {
     getLastSyncedTime();
-  }, 60000);
+  }, 5000);
```
Comment (Natim) [inline src/sidebar/panel.js]: This is #299 let me take it out of this PR

**Comment by Natim** [comment]
The better solution to avoid that, would be not to debounce the saving but I guess with IndexedDB it is a good thing to do it.
